name = "LieRinehart"
version = "0.1.0"
defaultTargets = ["LieRinehart"]

[[lean_lib]]
name = "LieRinehart"

# [[lean_exe]]
# name = "LieRinehart"
# root = "Main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.24.0"